---
title: 'Gene Annotation: Deng 2014'
author: "Kushal K Dey"
date: "February 23, 2016"
output: 
  html_document:
    css: floating-toc.css
    toc: true
---


```{r packages, echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE}
library(maptpx)
library(qtlcharts)
library(data.table)
library(mygene)
library(CountClust)
library(knitr)
```

## Overview

In this script, we perform the cluster annotations for the 6 clusters obtained for the Deng2014 data tracking development of cells into an embryo. 

## Loading the theta matrix 

```{r echo=TRUE, eval=TRUE}
deng_topics <- get(load("../rdas/deng_topic_fit.rda"))
#deng_topics <- get(load("rdas/deng_topic_fit.rda"))
theta_mat <- deng_topics[[5]]$theta;
top_features <- ExtractTopFeatures(theta_mat, top_features=100, method="poisson", options="min");
```

## Gene names 

```{r echo=TRUE, eval=TRUE}
gene_names <- rownames(theta_mat);
gene_list <- do.call(rbind, lapply(1:dim(top_features)[1], function(x) gene_names[top_features[x,]]))
```

### Cluster 1 annotations

```{r echo=TRUE, eval=TRUE}
out <- mygene::queryMany(gene_list[1,],  scopes="symbol", fields=c("name", "summary"), species="mouse");
kable(as.data.frame(out))
```

### Cluster 2 annotations

```{r echo=TRUE, eval=TRUE}
out <- mygene::queryMany(gene_list[2,],  scopes="symbol", fields=c("name", "summary"), species="mouse");
kable(as.data.frame(out))
```

### Cluster 3 annotations

```{r echo=TRUE, eval=TRUE}
out <- mygene::queryMany(gene_list[3,],  scopes="symbol", fields=c("name", "summary"), species="mouse");
kable(as.data.frame(out))
```

### Cluster 4 annotations

```{r echo=TRUE, eval=TRUE}
out <- mygene::queryMany(gene_list[4,],  scopes="symbol", fields=c("name", "summary"), species="mouse");
kable(as.data.frame(out))
```

### Cluster 5 annotations

```{r echo=TRUE, eval=TRUE}
out <- mygene::queryMany(gene_list[5,],  scopes="symbol", fields=c("name", "summary"), species="mouse");
kable(as.data.frame(out))
```

### Cluster 6 annotations

```{r echo=TRUE, eval=TRUE}
out <- mygene::queryMany(gene_list[6,],  scopes="symbol", fields=c("name", "summary"), species="mouse");
kable(as.data.frame(out))
```
