---
title: 'Plotting results of PCA vs. t-SNE: Deng'
author: "Joyce Hsiao"
date: "2016-09-12"
output: 
  html_document:
    css: floating-toc.css
    toc: true
---

```{r chunk-options, include=FALSE}
source("chunk-options.R")
```


```{r packages, echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE}
#library(maptpx)
library(ggplot2)
library(testit)
library(data.table)
library(mygene)
library(knitr)
```


## Objective

Make annotated plots for PCA and t-SNE results of Deng et al data.


## Setting up

Load Deng data

```{r load-deng-data, ech = TRUE, eval = TRUE}
library(singlecellRNAseqData)
MouseDengESC <- get(data("MouseDengESC"))
meta_data <- pData(MouseDengESC)
```

Load Deng t-SNE results that were prepared previously to save time.

```{r load-deng-tsne, echo=TRUE, eval=TRUE}
tsne_out <- get(load("../rdas/tsne_deng_data_k_2.rda"))
tsne_out <- as.matrix(tsne_out)
```

Load Deng MDS results

```{r load-deng-mds, echo = TRUE, eval = TRUE}
mds_out <- get(load("../rdas/mds_deng.rda"))
mds_out <- as.matrix(mds_out)
```


## Making plots

t-SNE plot

```{r ggplot-deng-tsne, echo = TRUE, eval = TRUE}
# name columns of tsne output
colnames(tsne_out) <- c("PC1", "PC2")

# combine in one data.frame tsne results with cell type labels 
plot_data_tsne <- cbind(tsne_out, meta_data)
plot_data_tsne <- as.data.frame(plot_data_tsne)

# make color scheme
cols <- c( rev(c("darkblue", "blue", "cornflowerblue", "cadetblue2")),
          rev(c("darkgreen", "darkolivegreen4", "darkolivegreen3")),
          rev(c("coral4", "coral3", "coral")) )
    
# make plot
tsne_plot <- ggplot(plot_data_tsne, aes(x = PC1, y = PC2)) + 
    geom_point(aes(fill = cell_type),
                   colour = "grey20", 
                   pch = 21, alpha = 1) +
    labs(x = "t-SNE 1st dimension", y = "t-SNE 2nd dimension") +
    scale_fill_manual(values = cols) +
    theme_classic() +
    theme(panel.border = element_rect(fill = "NA", colour = "black"))
```



PCA plot

```{r ggplot-deng-pca, echo = TRUE, eval = TRUE}
# transform to log2-CPM
counts <- exprs(MouseDengESC)
voom_data <- t(limma::voom(counts)$E)

# pca analysis
pc_out <- prcomp(voom_data)$x

# combine in one data.frame tsne results with cell type labels 
plot_data_pca <- cbind(pc_out[ ,c(1:2)], meta_data)
plot_data_pca <- as.data.frame(plot_data_pca)

# make color scheme
cols <- c( rev(c("darkblue", "blue", "cornflowerblue", "cadetblue2")),
          rev(c("darkgreen", "darkolivegreen4", "darkolivegreen3")),
          rev(c("coral4", "coral3", "coral")) )
    
# make plot
pca_plot <- ggplot(plot_data_pca, aes(x = PC1, y = PC2)) + 
    geom_point(aes(fill = cell_type),
                   colour = "grey20", 
                   pch = 21, alpha = 1) +
    labs(x = "PC1", y = "PC2") +
    scale_fill_manual(values = cols) +
    theme_classic() +
    theme(panel.border = element_rect(fill = "NA", colour = "black"))
```



MDS plot

```{r ggplot-deng-mds, echo = TRUE, eval = TRUE}
# name columns of MDS output
colnames(mds_out) <- c("dim1", "dim2")

# combine in one data.frame tsne results with cell type labels 
plot_data_mds <- cbind(mds_out, meta_data)
plot_data_mds <- as.data.frame(plot_data_mds)

# make color scheme
cols <- c( rev(c("darkblue", "blue", "cornflowerblue", "cadetblue2")),
          rev(c("darkgreen", "darkolivegreen4", "darkolivegreen3")),
          rev(c("coral4", "coral3", "coral")) )
    
# make plot
mds_plot <- ggplot(plot_data_mds, aes(x = dim1, y = dim2)) + 
    geom_point(aes(fill = cell_type),
                   colour = "grey20", 
                   pch = 21, alpha = 1) +
    labs(x = "MDS 1st dimension", y = "MDS 2nd dimension") +
    scale_fill_manual(values = cols) +
    theme_classic() +
    theme(panel.border = element_rect(fill = "NA", colour = "black"))
```


## Combined plot

```{r deng-combined-plot, fig.width=7, fig.height=7}
cowplot::plot_grid(
    pca_plot + theme(legend.position="none"), 
    tsne_plot  + theme(legend.position="none"),
    mds_plot + theme(legend.position="none"),
    labels = LETTERS[1:3])
```


Make legend

```{r make-legend, fig.height=4, fig.width=3}
coord_xy <- cbind(rep(1,10) - .4,
                  c(1:10))

library(pryr)
plot_legend %<a-% {
    plot(coord_xy, pch = 21, lwd = .8, 
        bg = rev(cols), col = "grey20",
        xlim = c(0, 17), ylim = c(0, 14),
        ann = F, axes = F)
    text(x = coord_xy[,1] + .8, y = coord_xy[,2],
         labels = rev(levels(factor(meta_data$cell_type))),
         cex = .6, adj = 0)
}
plot_legend
```


## Session information

```{r, eval = TRUE, echo = TRUE}
sessionInfo()
```

