---
title: 'Plotting results of PCA vs. t-SNE: Deng'
author: "Joyce Hsiao"
date: "2016-08-24"
output: 
  html_document:
    css: floating-toc.css
    toc: true
---

```{r chunk-options, include=FALSE}
source("chunk-options.R")
```


```{r packages, echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE}
#library(maptpx)
library(ggplot2)
library(testit)
library(data.table)
library(mygene)
library(knitr)
```


## Objective

Make annotated plots for PCA and t-SNE results of Deng et al data.


## Setting up

Load Deng data

```{r load-deng-data, ech = TRUE, eval = TRUE}
library(singlecellRNAseqData)
MouseDengESC <- get(data("MouseDengESC"))
meta_data <- pData(MouseDengESC)
```

Load Deng t-SNE results that were prepared previously to save time.

```{r load-deng-tsne, echo=TRUE, eval=TRUE}
tsne_out <- get(load("../rdas/tsne_deng_data_k_2.rda"))
tsne_out <- as.matrix(tsne_out)
```

## Making plots

t-SNE plot

```{r ggplot-deng-tsne, echo = TRUE, eval = TRUE}
# name columns of tsne output
colnames(tsne_out) <- c("PC1", "PC2")

# combine in one data.frame tsne results with cell type labels 
plot_data_tsne <- cbind(tsne_out, meta_data)
plot_data_tsne <- as.data.frame(plot_data_tsne)

# make color scheme
cols <- c("darkblue", 
          "blue", "cornflowerblue", "cadetblue2",
          "darkgreen", "darkolivegreen4", "darkolivegreen3",
          "coral4", "coral3", "coral")
    
# make plot
tsne_plot <- ggplot(plot_data_tsne, aes(x = PC1, y = PC2)) + 
    geom_point(aes(fill = cell_type),
                   colour = "grey20", 
                   pch = 21, alpha = 1) +
    labs(x = "t-SNE 1st dimension", y = "t-SNE 2nd dimension") +
    scale_fill_manual(values = cols) +
    theme_classic() +
    theme(panel.border = element_rect(fill = "NA", colour = "black"))
```



PCA plot

```{r ggplot-deng-pca, echo = TRUE, eval = TRUE}
# transform to log2-CPM
counts <- exprs(MouseDengESC)
voom_data <- t(limma::voom(counts)$E)

# pca analysis
pc_out <- prcomp(voom_data)$x

# combine in one data.frame tsne results with cell type labels 
plot_data_pca <- cbind(pc_out[ ,c(1:2)], meta_data)
plot_data_pca <- as.data.frame(plot_data_pca)

# make color scheme
cols <- c( rev(c("darkblue", "blue", "cornflowerblue", "cadetblue2")),
          rev(c("darkgreen", "darkolivegreen4", "darkolivegreen3")),
          rev(c("coral4", "coral3", "coral")) )
    
# make plot
pca_plot <- ggplot(plot_data_pca, aes(x = PC1, y = PC2)) + 
    geom_point(aes(fill = cell_type),
                   colour = "grey20", 
                   pch = 21, alpha = 1) +
    labs(x = "PC1", y = "PC2") +
    scale_fill_manual(values = cols) +
    theme_classic() +
    theme(panel.border = element_rect(fill = "NA", colour = "black"))
```


Dendrogram (to be completed)

```{r ggplot-deng-dendrogram, echo = TRUE, eval = FALSE}
dist_rda <- get(load("../rdas/euclidean_object_deng.rda"))
dist_mat <- as.matrix(dist_rda$euclidean_mat)

# make the metadata table
# that displays the corresponence between
# column names of the distance matrix and the 
# cell_type vector
labels_mat <- cbind(
    rownames(dist_rda$euclidean_mat),
    as.numeric(dist_rda$metadata$cell_type),
    levels(dist_rda$metadata$cell_type)[as.numeric(dist_rda$metadata$cell_type)])
labels_mat <- data.frame(labels_mat)
colnames(labels_mat) <- c("var_names", "cell_type", "cell_type_labels")

# use the R package dendextend 
# to make colored dendrogram
library(dendextend)
library(dendextendRcpp)
library(colorspace)

# make hclust object
dist_mat_hclust <- hclust(as.dist(dist_mat), method = "average")
dend <- as.dendrogram(dist_mat_hclust)

# rearrange labels table
# to re-order rows by the dendrogram node order
labels_mat <- labels_mat[match(labels(dend), labels_mat$var_names), ]

# make dendrogram
dend %>% set("labels", as.character(labels_mat$cell_type) ) %>%
    set("labels_colors") %>% 
    set("branches_k_color") %>% 
#   plot(horiz = TRUE) %>%
    plot
colored_bars(colors = labels_mat$cell_type,
             dend = dend)
```


## Combined plot

```{r deng-pca-tsne, fig.width=9, fig.height=9}
# plot the PCA plot twice
# first time without legend,
# and second time with legend
cowplot::plot_grid(
    pca_plot + theme(legend.position="none"), 
    tsne_plot  + theme(legend.position="none"),
    pca_plot, 
    labels = LETTERS[1:3])
```


## Session information

```{r, eval = TRUE, echo = TRUE}
sessionInfo()
```

