---
title: 'GTEx all tissue: Plotting results of other methods'
author: "Joyce Hsiao"
date: "2016-09-12"
output: 
  html_document:
    css: floating-toc.css
    toc: true
---

```{r chunk-options, include=FALSE}
source("chunk-options.R")
```


```{r packages, echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE}
#library(maptpx)
library(ggplot2)
library(testit)
library(data.table)
library(mygene)
library(knitr)
```



## Objective

Make annotated plots for visualizing results of t-SNE, PCA and MDS.


## Setting up

Load sample labels

```{r load-metadata, echo = TRUE, eval = TRUE}
sample_labels <- read.table("../rdas/samples-id-for-paper.txt",
                            header = TRUE, sep = "\t",
                            stringsAsFactors = FALSE)
sample_labels$SMTSD <- factor(sample_labels$SMTSD)
```


Load t-SNE data

```{r}
tsne_out <- read.table("../rdas/tsne_samples.txt", sep = "")
# name columns of tsne output
colnames(tsne_out) <- c("PC1", "PC2")
```

Load PCA results

```{r}
pca_out <- get(load("../rdas/pc_gtex_v6_x.rda"))
```

Load MDS data

```{r}
mds_out <- get(load("../rdas/mds_gtex_whole.rda"))
colnames(mds_out) <- c("dim1", "dim2")
```



Make color palette for gtex tissues

```{r gtex-color-wheel}
library(RColorBrewer)
n <- 53
qual_col_pals <- brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector <- unlist(mapply(brewer.pal, 
                    qual_col_pals$maxcolors, rownames(qual_col_pals)))
pie(rep(1,n), col=sample(col_vector, n), radius = 1)
```



## Making plots

t-SNE plot, using t-SNE reuslts of all genes

```{r ggplot-tsne, echo = TRUE, eval = TRUE}
# combine in one data.frame tsne results with cell type labels 
plot_data_tsne <- data.frame(tsne_out, sample_labels)
plot_data_tsne$SMTSD <- as.factor(plot_data_tsne$SMTSD)

# make plot
tsne_plot <- ggplot(plot_data_tsne, aes(x = PC1, y = PC2)) + 
    geom_point(aes(fill = SMTSD),
                   colour = "grey20", 
                   pch = 21, alpha = 1) +
    labs(x = "t-SNE 1st dimension", y = "t-SNE 2nd dimension") +
    scale_fill_manual(values = col_vector) +
    theme_classic() +
    theme(panel.border = element_rect(fill = "NA", colour = "black"))
```


PCA plot

```{r gtex-pca, echo = TRUE, eval = TRUE}
plot_data_pca <- data.frame(PC1 = pca_out[,1],
                            PC2 = pca_out[,2],
                            SMTSD = sample_labels$SMTSD)
plot_data_pca$SMTSD <- as.factor(plot_data_pca$SMTSD)

# make plot
pca_plot <- ggplot(plot_data_pca, aes(x = PC1, y = PC2)) + 
    geom_point(aes(fill = SMTSD),
                   colour = "grey20", 
                   pch = 21, alpha = 1) +
    labs(x = "PC1", y = "PC2") +
    scale_fill_manual(values = col_vector) +
    theme_classic() +
    theme(panel.border = element_rect(fill = "NA", colour = "black"))
```


MDS plot

```{r gtex-mds, echo = TRUE, eval = TRUE}
plot_data_mds <- data.frame(mds_out,
                            SMTSD = sample_labels$SMTSD)
plot_data_mds$SMTSD <- as.factor(plot_data_mds$SMTSD)

# make plot
mds_plot <- ggplot(plot_data_mds, aes(x = dim1, y = dim2)) + 
    geom_point(aes(fill = SMTSD),
                   colour = "grey20", 
                   pch = 21, alpha = 1) +
    labs(x = "PC1", y = "PC2") +
    scale_fill_manual(values = col_vector) +
    theme_classic() +
    theme(panel.border = element_rect(fill = "NA", colour = "black"))
```



## Combined plot

```{r gtex-pca-sne, fig.width=9, fig.height=9}
cowplot::plot_grid(
    pca_plot + theme(legend.position="none"), 
    tsne_plot  + theme(legend.position="none"),
    mds_plot  + theme(legend.position="none"),
    labels = LETTERS[1:3])
```


Make legend

```{r make-legend, fig.width=10,fig.height=5}
coord_xy <- cbind(c(rep(c(1,5,9,13), each = 13),13) - .4,
                  c(rep(c(13:1),4), 0))

library(pryr)
plot_legend %<a-% {
    plot(coord_xy, pch = 21, lwd = .8, 
        bg = col_vector, col = "grey20",
        xlim = c(0, 17), ylim = c(0, 14),
        ann = F, axes = F)
    text(x = coord_xy[,1] + .4, y = coord_xy[,2],
         labels = levels(factor(sample_labels$SMTSD)),
         cex = .6, adj = 0)
}
plot_legend
```

## Session information

```{r, eval = TRUE, echo = TRUE}
sessionInfo()
```

