
paper: manuscript-plos-gen-rev-1round.tex ../plots/gtex-figures/gtex-k20-05-01-2016.pdf ../plots/hierarchy_F_thin_0_1.png ../plots/admixture_F_thin_0_1.png ../plots/jaitin-figures/jaitin-main2.pdf ../plots/deng-figures/deng-main-v4.pdf ../plots/gtex-figures/gtex-k20-05-01-2016.pdf
	pdflatex manuscript-plos-gen-rev-1round.tex

clean:
	\rm -f *.aux *.bbl *.blg *.log *.bak *.out *.gz *~ *.Rout */*~ */*.Rout */*.aux */*.log */*.gz

cleanall:
	\rm -f *.aux *.bbl *.blg *.log *.bak *.out *~ *.Rout *.pdf */*~ */*.Rout */*.aux */*.log
