
paper: manuscript-plos-gen-rev-1round.tex 
	pdflatex manuscript-plos-gen-rev-1round.tex

clean:
	\rm -f *.aux *.bbl *.blg *.log *.bak *.out *.gz *~ *.Rout */*~ */*.Rout */*.aux */*.log */*.gz

cleanall:
	\rm -f *.aux *.bbl *.blg *.log *.bak *.out *~ *.Rout *.pdf */*~ */*.Rout */*.aux */*.log
